// <auto-generated />
using System;
using ClassicalApi.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassicalApi.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240409231057_AddMediaLink")]
    partial class AddMediaLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ClassicalApi.Core.Models.Composer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortraitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortBio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfDeath")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortraitId")
                        .IsUnique();

                    b.ToTable("Composers");
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.MediaLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaLinks");
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.Portrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Portraits");
                });

            modelBuilder.Entity("ComposerMediaLink", b =>
                {
                    b.Property<int>("ComposersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaLinksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComposersId", "MediaLinksId");

                    b.HasIndex("MediaLinksId");

                    b.ToTable("ComposerMediaLink");
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.Composer", b =>
                {
                    b.HasOne("ClassicalApi.Core.Models.Portrait", "Portrait")
                        .WithOne("Composer")
                        .HasForeignKey("ClassicalApi.Core.Models.Composer", "PortraitId");

                    b.Navigation("Portrait");
                });

            modelBuilder.Entity("ComposerMediaLink", b =>
                {
                    b.HasOne("ClassicalApi.Core.Models.Composer", null)
                        .WithMany()
                        .HasForeignKey("ComposersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassicalApi.Core.Models.MediaLink", null)
                        .WithMany()
                        .HasForeignKey("MediaLinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.Portrait", b =>
                {
                    b.Navigation("Composer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
