// <auto-generated />
using System;
using ClassicalApi.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassicalApi.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240317194729_AddPortraits")]
    partial class AddPortraits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ClassicalApi.Core.Models.Composer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortraitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortBio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfDeath")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Composers");
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.Portrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComposerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ComposerId")
                        .IsUnique();

                    b.ToTable("Portrait");
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.Portrait", b =>
                {
                    b.HasOne("ClassicalApi.Core.Models.Composer", "Composer")
                        .WithOne("Portrait")
                        .HasForeignKey("ClassicalApi.Core.Models.Portrait", "ComposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Composer");
                });

            modelBuilder.Entity("ClassicalApi.Core.Models.Composer", b =>
                {
                    b.Navigation("Portrait");
                });
#pragma warning restore 612, 618
        }
    }
}
