--
-- Файл сгенерирован с помощью SQLiteStudio v3.4.4 в Thu Apr 18 03:54:39 2024
--
-- Использованная кодировка текста: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: Composers
CREATE TABLE IF NOT EXISTS "Composers" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Composers" PRIMARY KEY AUTOINCREMENT,
    "CityOfBirth" TEXT NOT NULL,
    "CountryOfBirth" TEXT NOT NULL,
    "FirstName" TEXT NOT NULL,
    "LastName" TEXT NOT NULL,
    "PortraitId" INTEGER NULL,
    "ShortBio" TEXT NOT NULL,
    "YearOfBirth" INTEGER NULL,
    "YearOfDeath" INTEGER NULL,
    CONSTRAINT "FK_Composers_Portraits_PortraitId" FOREIGN KEY ("PortraitId") REFERENCES "Portraits" ("Id")
);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (1, 'Salzburg', 'Holy Roman Empire', 'Wolfgang Amadeus', 'Mozart', 22, ' Wolfgang Amadeus Mozart (27 January 1756 – 5 December 1791) was a prolific and influential composer of the Classical period. Despite his short life, his rapid pace of composition resulted in more than 800 works of virtually every Western classical genre of his time. Many of these compositions are acknowledged as pinnacles of the symphonic, concertante, chamber, operatic, and choral repertoire. Mozart is widely regarded as among the greatest composers in the history of Western music, with his music admired for its "melodic beauty, its formal elegance and its richness of harmony and texture".

Born in Salzburg, then in the Holy Roman Empire and currently in Austria, Mozart showed prodigious ability from his earliest childhood. Already competent on keyboard and violin, he composed from the age of five and performed before European royalty. His father took him on a grand tour of Europe and then three trips to Italy. At 17, he was a musician at the Salzburg court but grew restless and travelled in search of a better position.

While visiting Vienna in 1781, Mozart was dismissed from his Salzburg position. He stayed in Vienna, where he achieved fame but little financial security. During his final years there, he composed many of his best-known symphonies, concertos, and operas. His Requiem was largely unfinished by the time of his death at the age of 35, the circumstances of which are uncertain and much mythologised. ', 1756, 1791);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (2, 'Eisenach', 'Duchy of Saxe-Eisenach', 'Johann Sebastian', 'Bach', 23, 'Johann Sebastian Bach (31 March [O.S. 21 March] 1685 – 28 July 1750) was a German composer and musician of the late Baroque period. He is known for his orchestral music such as the Brandenburg Concertos; solo instrumental works such as the cello suites and sonatas and partitas for solo violin; keyboard works such as the Goldberg Variations and The Well-Tempered Clavier; organ works such as the Schubler Chorales and the Toccata and Fugue in D minor; and choral works such as the St Matthew Passion and the Mass in B minor.

The Bach family already counted several composers when Johann Sebastian was born as the last child of a city musician, Johann Ambrosius, in Eisenach. After being orphaned at the age of 10, he lived for five years with his eldest brother Johann Christoph, after which he continued his musical education in Lüneburg. From 1703 he was back in Thuringia, working as a musician for Protestant churches in Arnstadt and Mühlhausen and, for longer stretches of time, at courts in Weimar, where he expanded his organ repertory, and Köthen, where he was mostly engaged with chamber music. From 1723, he was employed as Thomaskantor (cantor at St Thomas''s) in Leipzig. There he composed music for the principal Lutheran churches of the city, and for its university''s student ensemble Collegium Musicum. From 1726, he published some of his keyboard and organ music. In Leipzig, as had happened during some of his earlier positions, he had difficult relations with his employer, a situation that was little remedied when he was granted the title of court composer by his sovereign, Augustus III of Poland, in 1736. In the last decades of his life, he reworked and extended many of his earlier compositions. He died of complications after a botched eye surgery in 1750 at the age of 65.

Bach enriched established German styles through his mastery of counterpoint, harmonic, and motivic organisation, and his adaptation of rhythms, forms, and textures from abroad, particularly from Italy and France. Bach''s compositions include hundreds of cantatas, both sacred and secular. He composed Latin church music, Passions, oratorios, and motets. He often adopted Lutheran hymns, not only in his larger vocal works, but for instance also in his four-part chorales and his sacred songs. He wrote extensively for organ and for other keyboard instruments. He composed concertos, for instance for violin and for harpsichord, and suites, as chamber music as well as for orchestra. Many of his works employ contrapuntal techniques like canon and fugue.

Throughout the 18th century, Bach was primarily valued as an organist, while his keyboard music, such as The Well-Tempered Clavier, was appreciated for its didactic qualities. In 1829, Felix Mendelssohn''s performance of the St Matthew Passion led to a Bach Revival. He has been generally regarded as one of the greatest composers in the history of Western music ever since.[3][4] The 19th century saw the publication of some major Bach biographies, and by the end of that century all of his known music had been printed. Dissemination of scholarship on the composer continued through periodicals (and later also websites) exclusively devoted to him, and other publications such as the Bach-Werke-Verzeichnis (BWV, a numbered catalogue of his works) and new critical editions of his compositions. His music was further popularised through a multitude of arrangements, including the Air on the G String and "Jesu, Joy of Man''s Desiring", and of recordings, such as three different box sets with complete performances of the composer''s oeuvre marking the 250th anniversary of his death. ', 1685, 1750);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (3, 'Bonn', 'Holy Roman Empire', 'Ludwig van', 'Beethoven', 26, 'Ludwig van Beethoven (baptised 17 December 1770 – 26 March 1827) was a German composer and pianist. He is one of the most revered figures in the history of Western music; his works rank among the most performed of the classical music repertoire and span the transition from the Classical period to the Romantic era in classical music. Beethoven''s career has conventionally been divided into early, middle, and late periods. His early period, during which he forged his craft, is typically considered to have lasted until 1802. From 1802 to around 1812, his middle period showed an individual development from the styles of Joseph Haydn and Wolfgang Amadeus Mozart, and is sometimes characterized as heroic. During this time, he began to grow increasingly deaf. In his late period, from 1812 to 1827, he extended his innovations in musical form and expression.

Born in Bonn, Beethoven displayed his musical talent at a young age. He was initially taught intensively by his father, Johann van Beethoven, and later by Christian Gottlob Neefe. Under Neefe''s tutelage in 1783, he published his first work, a set of keyboard variations. He found relief from a dysfunctional home life with the family of Helene von Breuning, whose children he loved, befriended, and taught piano. At age 21, he moved to Vienna, which subsequently became his base, and studied composition with Haydn. Beethoven then gained a reputation as a virtuoso pianist, and was soon patronised by Karl Alois, Prince Lichnowsky for compositions, which resulted in his three Opus 1 piano trios (the earliest works to which he accorded an opus number) in 1795.

His first major orchestral work, the First Symphony, premiered in 1800, and his first set of string quartets was published in 1801. Despite his hearing deteriorating during this period, he continued to conduct, premiering his Third and Fifth Symphonies in 1804 and 1808, respectively. His Violin Concerto appeared in 1806. His last piano concerto (No. 5, Op. 73, known as the Emperor), dedicated to his frequent patron Archduke Rudolf of Austria, premiered in 1811, without Beethoven as soloist. He was almost completely deaf by 1814, and he then gave up performing and appearing in public. He described his problems with health and his unfulfilled personal life in two letters, his Heiligenstadt Testament (1802) to his brothers and his unsent love letter to an unknown "Immortal Beloved" (1812).

After 1810, increasingly less socially involved, Beethoven composed many of his most admired works, including later symphonies, mature chamber music and the late piano sonatas. His only opera, Fidelio, first performed in 1805, was revised to its final version in 1814. He composed Missa solemnis between 1819 and 1823 and his final Symphony, No. 9, one of the first examples of a choral symphony, between 1822 and 1824. Written in his last years, his late string quartets, including the Grosse Fuge, of 1825–1826 are among his final achievements. After several months of illness, which left him bedridden, he died in 1827.', 1770, 1827);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (4, 'Rohrau', 'Holy Roman Empire', 'Franz Joseph', 'Haydn', 27, 'Franz Joseph Haydn (/ˈhaɪdən/ HY-dən, German: [ˈfʁants ˈjoːzɛf ˈhaɪdn̩]; 31 March 1732 – 31 May 1809) was an Austrian composer of the Classical period. He was instrumental in the development of chamber music such as the string quartet and piano trio. His contributions to musical form have led him to be called "Father of the Symphony" and "Father of the String quartet".

Haydn spent much of his career as a court musician for the wealthy Esterházy family at their Eszterháza Castle. Until the later part of his life, this isolated him from other composers and trends in music so that he was, as he put it, "forced to become original". Yet his music circulated widely, and for much of his career he was the most celebrated composer in Europe.

He was a friend and mentor of Mozart, a tutor of Beethoven, and the elder brother of composer Michael Haydn.', 1732, 1809);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (5, 'Halle', 'Duchy of Magdeburg', 'George Frideric', 'Handel', 28, 'George Frideric (or Frederick) Handel (/ˈhændəl/; baptised Georg Fried(e)rich Händel, German: [ˈɡeːɔʁk ˈfʁiːdʁɪç ˈhɛndl̩]; 23 February 1685 – 14 April 1759) was a German-British Baroque composer well known for his operas, oratorios, anthems, concerti grossi, and organ concertos. Handel received his training in Halle and worked as a composer in Hamburg and Italy before settling in London in 1712, where he spent the bulk of his career and became a naturalised British subject in 1727. He was strongly influenced both by the middle-German polyphonic choral tradition and by composers of the Italian Baroque. In turn, Handel''s music forms one of the peaks of the "high baroque" style, bringing Italian opera to its highest development, creating the genres of English oratorio and organ concerto, and introducing a new style into English church music. He is consistently recognized as one of the greatest composers of his age.

Handel started three commercial opera companies to supply the English nobility with Italian opera. In 1737, he had a physical breakdown, changed direction creatively, and addressed the middle class and made a transition to English choral works. After his success with Messiah (1742), he never composed an Italian opera again. His orchestral Water Music and Music for the Royal Fireworks remain steadfastly popular. One of his four coronation anthems, Zadok the Priest, has been performed at every British coronation since 1727. Almost blind, he died in 1759, a respected and rich man, and was given a state funeral at Westminster Abbey.

Handel composed more than forty opere serie over a period of more than thirty years. Since the late 1960s, interest in Handel''s music has grown. The musicologist Winton Dean wrote that "Handel was not only a great composer; he was a dramatic genius of the first order." His music was admired by Classical-era composers, especially Mozart, Haydn and Beethoven.', 1685, 1759);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (6, 'Żelazowa Wola', 'Poland', 'Frédéric François', 'Chopin', 29, 'Frédéric François Chopin (born Fryderyk Franciszek Chopin; 1 March 1810 – 17 October 1849) was a Polish composer and virtuoso pianist of the Romantic period, who wrote primarily for solo piano. He has maintained worldwide renown as a leading musician of his era, one whose "poetic genius was based on a professional technique that was without equal in his generation".

Chopin was born in Żelazowa Wola and grew up in Warsaw, which in 1815 became part of Congress Poland. A child prodigy, he completed his musical education and composed his earlier works in Warsaw before leaving Poland at the age of 20, less than a month before the outbreak of the November 1830 Uprising. At 21, he settled in Paris. Thereafter he gave only 30 public performances, preferring the more intimate atmosphere of the salon. He supported himself by selling his compositions and by giving piano lessons, for which he was in high demand. Chopin formed a friendship with Franz Liszt and was admired by many of his musical contemporaries, including Robert Schumann. After a failed engagement to Maria Wodzińska from 1836 to 1837, he maintained an often troubled relationship with the French writer Aurore Dupin (known by her pen name George Sand). A brief and unhappy visit to Mallorca with Sand in 1838–39 would prove one of his most productive periods of composition. In his final years, he was supported financially by his admirer Jane Stirling. For most of his life, Chopin was in poor health. He died in Paris in 1849 at the age of 39.

All of Chopin''s compositions feature the piano. Most are for solo piano, though he also wrote two piano concertos, some chamber music, and 19 songs set to Polish lyrics. His piano pieces are technically demanding and expanded the limits of the instrument; his own performances were noted for their nuance and sensitivity. Chopin''s major piano works include mazurkas, waltzes, nocturnes, polonaises, the instrumental ballade (which Chopin created as an instrumental genre), études, impromptus, scherzi, preludes, and sonatas, some published only posthumously. Among the influences on his style of composition were Polish folk music, the classical tradition of Mozart and Schubert, and the atmosphere of the Paris salons, of which he was a frequent guest. His innovations in style, harmony, and musical form, and his association of music with nationalism, were influential throughout and after the late Romantic period.

Chopin''s music, his status as one of music''s earliest celebrities, his indirect association with political insurrection, his high-profile love life, and his early death have made him a leading symbol of the Romantic era. His works remain popular, and he has been the subject of numerous films and biographies of varying historical fidelity. Among his many memorials is the Fryderyk Chopin Institute, which was created by the Parliament of Poland to research and promote his life and works. It hosts the International Chopin Piano Competition, a prestigious competition devoted entirely to his works.', 1810, 1849);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (7, 'Doborján', 'Austrian Empire', 'Franz', 'Liszt', 30, 'Franz Liszt (22 October 1811 – 31 July 1886) was a Hungarian composer, virtuoso pianist, conductor and teacher of the Romantic period. With a diverse body of work spanning more than six decades, he is considered to be one of the most prolific and influential composers of his era, and his piano works continue to be widely performed and recorded.

Liszt gained renown during the 1830s for his skill as a pianist. Regarded as one of the greatest pianists of the time, he toured Europe during the 1830s and 1840s, often playing for charity. In these years, Liszt developed a reputation for his powerful performances as well as his physical attractiveness. In a phenomenon dubbed "Lisztomania", he rose to a degree of stardom and popularity among the public not experienced by the virtuosos who preceded him.

During this period and into his later life, Liszt was a friend, musical promoter and benefactor to many composers of his time, including Hector Berlioz, Frédéric Chopin, Robert Schumann, Clara Schumann and Richard Wagner, among others. Alongside Wagner, Liszt was one of the most prominent representatives of the New German School, a progressive group of composers involved in the "War of the Romantics" who developed ideas of programmatic music and harmonic experimentation.

Liszt taught piano performance to hundreds of students throughout his life, many of whom went on to become notable performers. He left behind an extensive and diverse body of work that influenced his forward-looking contemporaries and anticipated 20th-century ideas and trends. Among Liszt''s musical contributions were the concept of the symphonic poem, innovations in thematic transformation and impressionism in music, and the invention of the masterclass as a method of teaching performance. In a radical departure from his earlier compositional styles, many of Liszt''s later works also feature experiments in atonality, foreshadowing developments in 20th-century classical music.', 1811, 1886);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (8, 'Leipzig', 'Kingdom of Saxony, Confederation of the Rhine', 'Richard', 'Wagner', 31, 'Wilhelm Richard Wagner (/ˈvɑːɡnər/ VAHG-nər; German: [ˈʁɪçaʁt ˈvaːɡnɐ]; 22 May 1813 – 13 February 1883) was a German composer, theatre director, polemicist, and conductor who is chiefly known for his operas (or, as some of his mature works were later known, "music dramas"). Unlike most opera composers, Wagner wrote both the libretto and the music for each of his stage works. Initially establishing his reputation as a composer of works in the romantic vein of Carl Maria von Weber and Giacomo Meyerbeer, Wagner revolutionised opera through his concept of the Gesamtkunstwerk ("total work of art"), by which he sought to synthesise the poetic, visual, musical and dramatic arts, with music subsidiary to drama. He described this vision in a series of essays published between 1849 and 1852. Wagner realised these ideas most fully in the first half of the four-opera cycle Der Ring des Nibelungen (The Ring of the Nibelung).

His compositions, particularly those of his later period, are notable for their complex textures, rich harmonies and orchestration, and the elaborate use of leitmotifs—musical phrases associated with individual characters, places, ideas, or plot elements. His advances in musical language, such as extreme chromaticism and quickly shifting tonal centres, greatly influenced the development of classical music. His Tristan und Isolde is sometimes described as marking the start of modern music.

Wagner had his own opera house built, the Bayreuth Festspielhaus, which embodied many novel design features. The Ring and Parsifal were premiered here and his most important stage works continue to be performed at the annual Bayreuth Festival, which was galvanized by the efforts of his wife Cosima Wagner and the family''s descendants. His thoughts on the relative contributions of music and drama in opera were to change again, and he reintroduced some traditional forms into his last few stage works, including Die Meistersinger von Nürnberg (The Mastersingers of Nuremberg).

Until his final years, Wagner''s life was characterised by political exile, turbulent love affairs, poverty and repeated flight from his creditors. His controversial writings on music, drama and politics have attracted extensive comment – particularly since the late 20th century, as they express antisemitic sentiments. The effect of his ideas can be traced in many of the arts throughout the 20th century; his influence spread beyond composition into conducting, philosophy, literature, the visual arts and theatre.', 1813, 1883);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (9, 'Saint-Germain-en-Laye, Seine-et-Oise', 'France', 'Achille-Claude', 'Debussy', 32, '(Achille) Claude Debussy (French: [aʃil klod dəbysi]; 22 August 1862 – 25 March 1918) was a French composer. He is sometimes seen as the first Impressionist composer, although he vigorously rejected the term. He was among the most influential composers of the late 19th and early 20th centuries.

Born to a family of modest means and little cultural involvement, Debussy showed enough musical talent to be admitted at the age of ten to France''s leading music college, the Conservatoire de Paris. He originally studied the piano, but found his vocation in innovative composition, despite the disapproval of the Conservatoire''s conservative professors. He took many years to develop his mature style, and was nearly 40 when he achieved international fame in 1902 with the only opera he completed, Pelléas et Mélisande.

Debussy''s orchestral works include Prélude à l''après-midi d''un faune (1894), Nocturnes (1897–1899) and Images (1905–1912). His music was to a considerable extent a reaction against Wagner and the German musical tradition. He regarded the classical symphony as obsolete and sought an alternative in his "symphonic sketches", La mer (1903–1905). His piano works include sets of 24 Préludes and 12 Études. Throughout his career he wrote mélodies based on a wide variety of poetry, including his own. He was greatly influenced by the Symbolist poetic movement of the later 19th century. A small number of works, including the early La Damoiselle élue and the late Le Martyre de saint Sébastien have important parts for chorus. In his final years, he focused on chamber music, completing three of six planned sonatas for different combinations of instruments.

With early influences including Russian and Far Eastern music and works by Chopin, Debussy developed his own style of harmony and orchestral colouring, derided – and unsuccessfully resisted – by much of the musical establishment of the day. His works have strongly influenced a wide range of composers including Béla Bartók, Olivier Messiaen, George Benjamin, and the jazz pianist and composer Bill Evans. Debussy died from cancer at his home in Paris at the age of 55 after a composing career of a little more than 30 years.', 1862, 1918);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (10, 'Munich', 'Kingdom of Bavaria, German Confederation', 'Richard', 'Strauss', NULL, ' ', 1864, 1949);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (11, 'Kaliště', 'Kingdom of Bohemia, Austrian Empire', 'Gustav', 'Mahler', 43, 'Gustav Mahler (German: [ˈɡʊstaf ˈmaːlɐ]; 7 July 1860 – 18 May 1911) was an Austro-Bohemian Romantic composer, and one of the leading conductors of his generation. As a composer he acted as a bridge between the 19th-century Austro-German tradition and the modernism of the early 20th century. While in his lifetime his status as a conductor was established beyond question, his own music gained wide popularity only after periods of relative neglect, which included a ban on its performance in much of Europe during the Nazi era. After 1945 his compositions were rediscovered by a new generation of listeners; Mahler then became one of the most frequently performed and recorded of all composers, a position he has sustained into the 21st century.

Born in Bohemia (then part of the Austrian Empire) to Jewish parents of humble origins, the German-speaking Mahler displayed his musical gifts at an early age. After graduating from the Vienna Conservatory in 1878, he held a succession of conducting posts of rising importance in the opera houses of Europe, culminating in his appointment in 1897 as director of the Vienna Court Opera (Hofoper). During his ten years in Vienna, Mahler—who had converted to Catholicism to secure the post—experienced regular opposition and hostility from the anti-Semitic press. Nevertheless, his innovative productions and insistence on the highest performance standards ensured his reputation as one of the greatest of opera conductors, particularly as an interpreter of the stage works of Wagner, Mozart, and Tchaikovsky. Late in his life he was briefly director of New York''s Metropolitan Opera and the New York Philharmonic.

Mahler''s œuvre is relatively limited; for much of his life composing was necessarily a part-time activity while he earned his living as a conductor. Aside from early works such as a movement from a piano quartet composed when he was a student in Vienna, Mahler''s works are generally designed for large orchestral forces, symphonic choruses and operatic soloists. These works were frequently controversial when first performed, and several were slow to receive critical and popular approval; exceptions included his Second Symphony, and the triumphant premiere of his Eighth Symphony in 1910. Some of Mahler''s immediate musical successors included the composers of the Second Viennese School, notably Arnold Schoenberg, Alban Berg and Anton Webern. Dmitri Shostakovich and Benjamin Britten are among later 20th-century composers who admired and were influenced by Mahler. The International Gustav Mahler Society was established in 1955 to honour the composer''s life and achievements. ', 1860, 1911);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (12, 'Tikhvin', 'Russian Empire', 'Nikolai Andreyevich', 'Rimsky-Korsakov', 44, 'Nikolai Andreyevich Rimsky-Korsakov (18 March 1844 – 21 June 1908) was a Russian composer, a member of the group of composers known as The Five. He was a master of orchestration. His best-known orchestral compositions — 
Capriccio Espagnol, the Russian Easter Festival Overture, and the symphonic suite Scheherazade — are staples of the classical music repertoire, along with suites and excerpts from some of his fifteen operas. Scheherazade is an example of his frequent use of fairy-tale and folk subjects.

Rimsky-Korsakov believed in developing a nationalistic style of classical music, as did his fellow composer Mily Balakirev and the critic Vladimir Stasov. This style employed Russian folk song and lore along with exotic harmonic, melodic and rhythmic elements in a practice known as musical orientalism, and eschewed traditional Western compositional methods. Rimsky-Korsakov appreciated Western musical techniques after he became a professor of musical composition, harmony, and orchestration at the Saint Petersburg Conservatory in 1871. He undertook a rigorous three-year program of self-education and became a master of Western methods, incorporating them alongside the influences of Mikhail Glinka and fellow members of The Five. Rimsky-Korsakov''s techniques of composition and orchestration were further enriched by his exposure to the works of Richard Wagner.

For much of his life, Rimsky-Korsakov combined his composition and teaching with a career in the Russian armed forces — first as an officer in the Imperial Russian Navy, then as the civilian Inspector of Naval Bands. He wrote that he developed a passion for the ocean in childhood from reading books and hearing of his older brother''s exploits in the navy. This love of the sea may have influenced him to write two of his best-known orchestral works, the musical tableau Sadko (not to be confused with his later opera of the same name) and Scheherazade. As Inspector of Naval Bands, Rimsky-Korsakov expanded his knowledge of woodwind and brass playing, which enhanced his abilities in orchestration. He passed this knowledge to his students, and also posthumously through a textbook on orchestration that was completed by his son-in-law Maximilian Steinberg.

Rimsky-Korsakov left a considerable body of original Russian nationalist compositions. He prepared works by The Five for performance, which brought them into the active classical repertoire (although there is controversy over his editing of the works of Modest Mussorgsky), and shaped a generation of younger composers and musicians during his decades as an educator. Rimsky-Korsakov is therefore considered "the main architect" of what the classical-music public considers the "Russian style". His influence on younger composers was especially important, as he served as a transitional figure between the autodidactism exemplified by Glinka and The Five, and professionally trained composers, who became the norm in Russia by the closing years of the 19th century. While Rimsky-Korsakov''s style was based on those of Glinka, Balakirev, Hector Berlioz, Franz Liszt and, for a brief period, Wagner, he "transmitted this style directly to two generations of Russian composers" and influenced non-Russian composers including Maurice Ravel, Claude Debussy, Paul Dukas, and Ottorino Respighi.', 1864, 1908);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (13, 'Karevo', 'Russian Empire', 'Modest Petrovich', 'Mussorgsky', 45, 'Modest Petrovich Mussorgsky (Russian: Модест Петрович Мусоргский, tr. Modest Petrovich Musorgsky, IPA: [mɐˈdɛst pʲɪˈtrovʲɪtɕ ˈmusərkskʲɪj] 21 March [O.S. 9 March] 1839 – 28 March [O.S. 16 March] 1881) was a Russian composer, one of the group known as "The Five". He was an innovator of Russian music in the Romantic period. He strove to achieve a uniquely Russian musical identity, often in deliberate defiance of the established conventions of Western music.

Many of his works were inspired by Russian history, Russian folklore, and other national themes. Such works include the opera Boris Godunov, the orchestral tone poem Night on Bald Mountain and the piano suite Pictures at an Exhibition.

For many years, Mussorgsky''s works were mainly known in versions revised or completed by other composers. Many of his most important compositions have posthumously come into their own in their original forms, and some of the original scores are now also available. ', 1839, 1881);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (14, 'Novospasskoye', 'Russian Empire', 'Mikhail Ivanovich', 'Glinka', 46, 'Mikhail Ivanovich Glinka (1804–1857) was a Russian composer, regarded as the first to become very famous.

Russia is a very large country. In the 18th century there was a lot of music in Europe, but Russian people had not yet heard it. A lot of them were very poor and modern transport did not exist. By the time Glinka was born Russian people in the large towns like Saint Petersburg were becoming very interested in European music.

Mikhail Glinka was born in a little village called Novospasskoye. His father was a rich landowner. Glinka was brought up by his grandmother who looked after him very carefully. She was always afraid he would be cold, so she wrapped him up in a fur coat in a room which was kept at 77 °F. He was not often allowed to play in the fresh air. Later in his life Glinka was always worrying about his health.

It was a long way to the big cities from where the child lived. There was no radio in those days, and no CDs. The only music he heard was the church bells, and the singing of the peasants (the simple people who worked on the land). They sang folksongs and made up harmony underneath the tunes.

After his grandmother died he was allowed to travel 6 miles to his uncle’s home. His uncle had a group of musicians who played music by European composers like Haydn, Mozart and Beethoven. He had never heard such music before.

When he was 13 he went to school in St Petersburg. Now he could hear lots of music and meet some good musicians. He had piano lessons and spent a lot of time at parties. He started to compose some songs.

In 1830 he went to Italy. Italy was famous for its music, especially for opera. Glinka met famous composers like Mendelssohn and Berlioz as well as Italian composers like Donizetti and Bellini. He like their music, and decided he wanted to write opera as well, but he wanted to make his music sound very Russian.

Glinka went back to Russia. He wrote two great operas. The first one was called Ivan Susanin. The story of the opera, set in 1612, is about a poor peasant Ivan Susanin who dies to save the life of the Tsar (the Tsar was the ruler of Russia, like a king or emperor). The Tsar liked the opera and thought that it should be called A Life for the Tsar. It was a big success when it was first performed in 1836.

He soon wrote his second opera: Ruslan and Lyudmila. The story comes from a tale by the famous Russian poet Pushkin. The man who wrote the words for him did it very quickly while he was drunk, so the story is a bit muddled, but the music is wonderful. It is a fairy tale about a nasty dwarf Chernomor who has taken away a princess called Lyudmila. In the end Ruslan, the hero, rescues her. Some of the music sounds quite oriental. The overture that starts the opera is very famous.

Glinka also wrote piano music, songs and chamber music.

Glinka’s music is important because he was the first Russian composer to write music that sounded Russian. Later composers like Tchaikovsky were influenced by his music. ', 1804, 1857);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (15, 'Himmelpfortgrund', 'Holy Roman Empire', 'Franz Peter', 'Schubert', 47, 'Franz Peter Schubert (German: [fʁants ˈpeːtɐ ˈʃuːbɐt]; 31 January 1797 – 19 November 1828) was an Austrian composer of the late Classical and early Romantic eras. Despite his short life, Schubert left behind a vast oeuvre, including more than 600 secular vocal works (mainly lieder), seven complete symphonies, sacred music, operas, incidental music, and a large body of piano and chamber music. His major works include the art songs "Erlkönig", "Gretchen am Spinnrade", "Ave Maria"; the Trout Quintet, the unfinished Symphony No. 8 in B minor, the "Great" Symphony No. 9 in C major, the String Quartet No. 14 Death and the Maiden, a String Quintet, the two sets of Impromptus for solo piano, the three last piano sonatas, the Fantasia in F minor for piano four hands, the opera Fierrabras, the incidental music to the play Rosamunde, and the song cycles Die schöne Müllerin, Winterreise and Schwanengesang.

Born in the Himmelpfortgrund suburb of Vienna, Schubert showed uncommon gifts for music from an early age. His father gave him his first violin lessons and his elder brother gave him piano lessons, but Schubert soon exceeded their abilities. In 1808, at the age of eleven, he became a pupil at the Stadtkonvikt school, where he became acquainted with the orchestral music of Joseph Haydn, Wolfgang Amadeus Mozart, and Ludwig van Beethoven. He left the Stadtkonvikt at the end of 1813 and returned home to live with his father, where he began studying to become a schoolteacher. Despite this, he continued his studies in composition with Antonio Salieri and still composed prolifically. In 1821, Schubert was admitted to the Gesellschaft der Musikfreunde as a performing member, which helped establish his name among the Viennese citizenry. He gave a concert of his works to critical acclaim in March 1828, the only time he did so in his career. He died eight months later at the age of 31, the cause officially attributed to typhoid fever, but believed by some historians to be syphilis.

Appreciation of Schubert''s music while he was alive was limited to a relatively small circle of admirers in Vienna, but interest in his work increased greatly in the decades following his death. Felix Mendelssohn, Robert Schumann, Franz Liszt, Johannes Brahms and other 19th-century composers discovered and championed his works. Today, Schubert is ranked among the greatest composers in the history of Western classical music and his work continues to be admired and widely performed. ', 1797, 1828);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (16, 'Ciboure', 'France', 'Joseph Maurice', 'Ravel', 49, 'Joseph Maurice Ravel (7 March 1875 – 28 December 1937) was a French composer, pianist and conductor. He is often associated with Impressionism along with his elder contemporary Claude Debussy, although both composers rejected the term. In the 1920s and 1930s Ravel was internationally regarded as France''s greatest living composer.

Born to a music-loving family, Ravel attended France''s premier music college, the Paris Conservatoire; he was not well regarded by its conservative establishment, whose biased treatment of him caused a scandal. After leaving the conservatoire, Ravel found his own way as a composer, developing a style of great clarity and incorporating elements of modernism, baroque, neoclassicism and, in his later works, jazz. He liked to experiment with musical form, as in his best-known work, Boléro (1928), in which repetition takes the place of development. Renowned for his abilities in orchestration, Ravel made some orchestral arrangements of other composers'' piano music, of which his 1922 version of Mussorgsky''s Pictures at an Exhibition is the best known.

A slow and painstaking worker, Ravel composed fewer pieces than many of his contemporaries. Among his works to enter the repertoire are pieces for piano, chamber music, two piano concertos, ballet music, two operas and eight song cycles; he wrote no symphonies or church music. Many of his works exist in two versions: first, a piano score and later an orchestration. Some of his piano music, such as Gaspard de la nuit (1908), is exceptionally difficult to play, and his complex orchestral works such as Daphnis et Chloé (1912) require skilful balance in performance.

Ravel was among the first composers to recognise the potential of recording to bring their music to a wider public. From the 1920s, despite limited technique as a pianist or conductor, he took part in recordings of several of his works; others were made under his supervision. ', 1875, 1937);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (17, 'Sontsovka', 'Russian Empire', 'Sergei Sergeyevich', 'Prokofiev', 48, 'Sergei Sergeyevich Prokofiev (27 April [O.S. 15 April] 1891 – 5 March 1953) was a Russian composer, pianist, and conductor who later worked in the Soviet Union. As the creator of acknowledged masterpieces across numerous music genres, he is regarded as one of the major composers of the 20th century. His works include such widely heard pieces as the March from The Love for Three Oranges, the suite Lieutenant Kijé, the ballet Romeo and Juliet—from which "Dance of the Knights" is taken—and Peter and the Wolf. Of the established forms and genres in which he worked, he created—excluding juvenilia—seven completed operas, seven symphonies, eight ballets, five piano concertos, two violin concertos, a cello concerto, a symphony-concerto for cello and orchestra, and nine completed piano sonatas.

A graduate of the Saint Petersburg Conservatory, Prokofiev initially made his name as an iconoclastic composer-pianist, achieving notoriety with a series of ferociously dissonant and virtuosic works for his instrument, including his first two piano concertos. In 1915, Prokofiev made a decisive break from the standard composer-pianist category with his orchestral Scythian Suite, compiled from music originally composed for a ballet commissioned by Sergei Diaghilev of the Ballets Russes. Diaghilev commissioned three further ballets from Prokofiev—Chout, Le pas d''acier and The Prodigal Son—which, at the time of their original production, all caused a sensation among both critics and colleagues. But Prokofiev''s greatest interest was opera, and he composed several works in that genre, including The Gambler and The Fiery Angel. Prokofiev''s one operatic success during his lifetime was The Love for Three Oranges, composed for the Chicago Opera and performed over the following decade in Europe and Russia.

After the Revolution of 1917, Prokofiev left Russia with the approval of Soviet People''s Commissar Anatoly Lunacharsky, and resided in the United States, then Germany, then Paris, making his living as a composer, pianist and conductor. In 1923 he married a Spanish singer, Carolina (Lina) Codina, with whom he had two sons; they divorced in 1947. In the early 1930s, the Great Depression diminished opportunities for Prokofiev''s ballets and operas to be staged in America and Western Europe. Prokofiev, who regarded himself as a composer foremost, resented the time taken by touring as a pianist, and increasingly turned to the Soviet Union for commissions of new music; in 1936, he finally returned to his homeland with his family. His greatest Soviet successes included Lieutenant Kijé, Peter and the Wolf, Romeo and Juliet, Cinderella, Alexander Nevsky, the Fifth and Sixth Symphonies, On Guard for Peace, and the Piano Sonatas Nos. 6–8.

The Nazi invasion of the USSR spurred Prokofiev to compose his most ambitious work, an operatic version of Leo Tolstoy''s War and Peace; he co-wrote the libretto with Mira Mendelson, his longtime companion and later second wife. In 1948, Prokofiev was attacked for producing "anti-democratic formalism". Nevertheless, he enjoyed personal and artistic support from a new generation of Russian performers, notably Sviatoslav Richter and Mstislav Rostropovich: he wrote his Ninth Piano Sonata for the former and his Symphony-Concerto for the latter. ', 1891, 1953);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (18, 'Saint Petersburg', 'Russian Empire', 'Dmitri Dmitriyevich', 'Shostakovich', 42, 'Dmitri Dmitriyevich Shostakovich (25 September [O.S. 12 September] 1906 – 9 August 1975) was a Soviet-era Russian composer and pianist who became internationally known after the premiere of his First Symphony in 1926 and thereafter was regarded as a major composer.

Shostakovich achieved early fame in the Soviet Union, but had a complex relationship with its government. His 1934 opera Lady Macbeth of Mtsensk was initially a success, but eventually was condemned by the Soviet government, putting his career at risk. In 1948 his work was denounced under the Zhdanov Doctrine, with professional consequences lasting several years. Even after his censure was rescinded in 1956, performances of his music were occasionally subject to state interventions, as with his Thirteenth Symphony (1962). Shostakovich was a member of the Supreme Soviet of the RSFSR (1947) and the Supreme Soviet of the Soviet Union (from 1962 until his death), as well as chairman of the RSFSR Union of Composers (1960–1968). Over the course of his career, he earned several important awards, including the Order of Lenin, from the Soviet government.

Shostakovich combined a variety of different musical techniques in his works. His music is characterized by sharp contrasts, elements of the grotesque, and ambivalent tonality; he was also heavily influenced by neoclassicism and by the late Romanticism of Gustav Mahler. His orchestral works include 15 symphonies and six concerti (two each for piano, violin, and cello). His chamber works include 15 string quartets, a piano quintet, and two piano trios. His solo piano works include two sonatas, an early set of 24 preludes, and a later set of 24 preludes and fugues. Stage works include three completed operas and three ballets. Shostakovich also wrote several song cycles, and a substantial quantity of music for theatre and film.

Shostakovich''s reputation has continued to grow after his death. Scholarly interest has increased significantly since the late 20th century, including considerable debate about the relationship between his music and his attitudes toward the Soviet government.', 1906, 1975);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (19, 'Votkinsk', 'Russian Empire', 'Pyotr Ilyich', 'Tchaikovsky', 24, 'Pyotr Ilyich Tchaikovsky (/tʃaɪˈkɒfski/ chy-KOF-skee; 7 May 1840 – 6 November 1893) was a Russian composer of the Romantic period. He was the first Russian composer whose music would make a lasting impression internationally. Tchaikovsky wrote some of the most popular concert and theatrical music in the current classical repertoire, including the ballets Swan Lake and The Nutcracker, the 1812 Overture, his First Piano Concerto, Violin Concerto, the Romeo and Juliet Overture-Fantasy, several symphonies, and the opera Eugene Onegin.

Although musically precocious, Tchaikovsky was educated for a career as a civil servant as there was little opportunity for a musical career in Russia at the time and no system of public music education. When an opportunity for such an education arose, he entered the nascent Saint Petersburg Conservatory, from which he graduated in 1865. The formal Western-oriented teaching that Tchaikovsky received there set him apart from composers of the contemporary nationalist movement embodied by the Russian composers of The Five with whom his professional relationship was mixed.

Tchaikovsky''s training set him on a path to reconcile what he had learned with the native musical practices to which he had been exposed from childhood. From that reconciliation, he forged a personal but unmistakably Russian style. The principles that governed melody, harmony, and other fundamentals of Russian music diverged from those that governed Western European music, which seemed to defeat the potential for using Russian music in large-scale Western composition or for forming a composite style, and it caused personal antipathies that dented Tchaikovsky''s self-confidence. Russian culture exhibited a split personality, with its native and adopted elements having drifted apart increasingly since the time of Peter the Great. That resulted in uncertainty among the intelligentsia about the country''s national identity, an ambiguity mirrored in Tchaikovsky''s career.

Despite his many popular successes, Tchaikovsky''s life was punctuated by personal crises and depression. Contributory factors included his early separation from his mother for boarding school followed by his mother''s early death, the death of his close friend and colleague Nikolai Rubinstein, his failed marriage with Antonina Miliukova, and the collapse of his 13-year association with the wealthy patroness Nadezhda von Meck. Tchaikovsky''s homosexuality, which he kept private, has traditionally also been considered a major factor though some scholars have played down its importance. His dedication of his Sixth symphony to his nephew Vladimir "Bob" Davydov and his feelings expressed about Davydov in letters to others, especially following Davydov''s suicide, have been cited as evidence for a romantic love between the two. Tchaikovsky''s sudden death at the age of 53 is generally ascribed to cholera, but there is an ongoing debate as to whether cholera was indeed the cause and whether the death was accidental or intentional.

While his music has remained popular among audiences, critical opinions were initially mixed. Some Russians did not feel it was sufficiently representative of native musical values and expressed suspicion that Europeans accepted the music for its Western elements. In an apparent reinforcement of the latter claim, some Europeans lauded Tchaikovsky for offering music more substantive than exoticism, and said he transcended the stereotypes of Russian classical music. Others dismissed Tchaikovsky''s music as deficient because it did not stringently follow Western principles. ', 1840, 1893);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (20, 'Semyonovo', 'Russian Empire', 'Sergei Vasilyevich', 'Rachmaninoff', 25, 'Sergei Vasilyevich Rachmaninoff (1 April [O.S. 20 March] 1873 – 28 March 1943) was a Russian composer, virtuoso pianist, and conductor. Rachmaninoff is widely considered one of the finest pianists of his day and, as a composer, one of the last great representatives of Romanticism in Russian classical music. Early influences of Tchaikovsky, Rimsky-Korsakov, and other Russian composers gave way to a thoroughly personal idiom notable for its song-like melodicism, expressiveness, dense contrapuntal textures, and rich orchestral colours. The piano is featured prominently in Rachmaninoff''s compositional output and he used his skills as a performer to fully explore the expressive and technical possibilities of the instrument.

Born into a musical family, Rachmaninoff began learning the piano at the age of four. He studied piano and composition at the Moscow Conservatory, from which he graduated in 1892, having already written several compositions. In 1897, following the disastrous premiere of his Symphony No. 1, Rachmaninoff entered a four-year depression and composed little, until supportive therapy allowed him to complete his well-received Piano Concerto No. 2 in 1901. Rachmaninoff went on to become conductor of the Bolshoi Theatre from 1904–06, and relocated to Dresden, Germany, in 1906. He later embarked upon his first tour of the United States as a pianist in 1909.

After the Russian Revolution, Rachmaninoff and his family left Russia permanently, settling in New York in 1918. Following this, he spent most of his time touring as a pianist through the US and Europe, from 1932 onwards spending his summers at his villa in Switzerland. During this time, Rachmaninoff''s primary occupation was performing, and his compositional output decreased significantly, completing just six works after leaving Russia. By 1942, his declining health led him to move to Beverly Hills, California, where he died from melanoma in 1943. ', 1873, 1944);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (21, 'Oranienbaum', 'Russian Empire', 'Igor Fyodorovich', 'Stravinsky', 33, 'Igor Fyodorovich Stravinsky (17 June [O.S. 5 June] 1882 – 6 April 1971) was a Russian composer and conductor with French citizenship (from 1934) and United States citizenship (from 1945). He is widely considered one of the most important and influential composers of the 20th century and a pivotal figure in modernist music.

Stravinsky''s father was an established bass opera singer, and Stravinsky grew up taking piano and music theory lessons. While studying law at the University of Saint Petersburg, he met Nikolai Rimsky-Korsakov and studied under him until Rimsky-Korsakov''s death in 1908. Stravinsky met the impresario Sergei Diaghilev soon after, who commissioned Stravinsky to write three ballets: The Firebird (1910), Petrushka (1911), and The Rite of Spring (1913), the last of which brought him international fame after the near-riot at the premiere, and changed the way composers understood rhythmic structure.

Stravinsky''s compositional career is divided into three periods: his Russian period (1913–1920), his neoclassical period (1920–1951), and his serial period (1954–1968). Stravinsky''s Russian period was characterised by influence from Russian styles and folklore. Renard (1916) and Les noces (1923) were based on Russian folk poetry, and works like L''Histoire du soldat blended these folktales with popular musical structures, like the tango, waltz, rag, and chorale. His neoclassical period exhibited themes and techniques from the classical period, like the use of the sonata form in his Octet (1923) and use of Greek mythological themes in works like Apollon musagète (1927), Oedipus rex (1927), and Persephone (1935). In his serial period, Stravinsky turned towards compositional techniques from the Second Viennese School like Arnold Schoenberg''s twelve-tone technique. In Memoriam Dylan Thomas (1954) was the first of his compositions to be fully based on the technique, and Canticum Sacrum (1956) was his first to be based on a tone row. Stravinsky''s last major work was the Requiem Canticles (1966), which was performed at his funeral.

While some composers and academics of the time disliked the avant-garde nature of Stravinsky''s music, particularly The Rite of Spring, later writers recognized his importance to the development of modernist music. Stravinsky''s revolutions of rhythm and modernism influenced composers like Aaron Copland, Philip Glass, Béla Bartók, and Pierre Boulez, all of whom "felt impelled to face the challenges set by [The Rite of Spring]," as George Benjamin wrote in The Guardian. In 1998, Time magazine named Stravinsky one of the 100 most influential people of the century. Stravinsky died of pulmonary edema on 6 April 1971 in New York City.', 1882, 1971);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (22, 'Moscow', 'Russian Empire', 'Andrey', 'Skryabin', 34, 'Alexander Nikolayevich Scriabin (6 January 1872 [O.S. 25 December 1871] – 27 April [O.S. 14 April] 1915) was a Russian composer and virtuoso pianist. Before 1903, Scriabin was greatly influenced by the music of Frédéric Chopin and composed in a relatively tonal, late-Romantic idiom. Later, and independently of his influential contemporary Arnold Schoenberg, Scriabin developed a much more dissonant musical language that had transcended usual tonality but was not atonal, which accorded with his personal brand of metaphysics. Scriabin found significant appeal in the concept of Gesamtkunstwerk as well as synesthesia, and associated colours with the various harmonic tones of his scale, while his colour-coded circle of fifths was also inspired by theosophy. He is often considered the main Russian Symbolist composer and a major representative of the Russian Silver Age.

Scriabin was an innovator as well as one of the most controversial composer-pianists of the early 20th century. The Great Soviet Encyclopedia said of him, "no composer has had more scorn heaped on him or greater love bestowed." Leo Tolstoy described Scriabin''s music as "a sincere expression of genius." Scriabin''s oeuvre exerted a salient influence on the music world over time, and inspired composers such as Igor Stravinsky, Sergei Prokofiev, and Karol Szymanowski. But Scriabin''s importance in the Russian (subsequently Soviet) musical scene, and internationally, drastically declined after his death. According to his biographer Faubion Bowers, "No one was more famous during their lifetime, and few were more quickly ignored after death." Nevertheless, his musical aesthetics have been reevaluated since the 1970s, and his ten published sonatas for piano and other works have been increasingly championed, garnering significant acclaim in recent years.', 1871, 1915);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (23, 'Paris', 'France', 'Camille', 'Saint-Saëns', 35, 'Charles-Camille Saint-Saëns (UK: /ˈsæ̃sɒ̃(s)/, US: /sæ̃ˈsɒ̃(s)/, French: [ʃaʁl kamij sɛ̃ sɑ̃(s)]; 9 October 1835 – 16 December 1921) was a French composer, organist, conductor and pianist of the Romantic era. His best-known works include Introduction and Rondo Capriccioso (1863), the Second Piano Concerto (1868), the First Cello Concerto (1872), Danse macabre (1874), the opera Samson and Delilah (1877), the Third Violin Concerto (1880), the Third ("Organ") Symphony (1886) and The Carnival of the Animals (1886).

Saint-Saëns was a musical prodigy; he made his concert debut at the age of ten. After studying at the Paris Conservatoire he followed a conventional career as a church organist, first at Saint-Merri, Paris and, from 1858, La Madeleine, the official church of the French Empire. After leaving the post twenty years later, he was a successful freelance pianist and composer, in demand in Europe and the Americas.

As a young man, Saint-Saëns was enthusiastic for the most modern music of the day, particularly that of Schumann, Liszt and Wagner, although his own compositions were generally within a conventional classical tradition. He was a scholar of musical history, and remained committed to the structures worked out by earlier French composers. This brought him into conflict in his later years with composers of the impressionist and expressionist schools of music; although there were neoclassical elements in his music, foreshadowing works by Stravinsky and Les Six, he was often regarded as a reactionary in the decades around the time of his death.

Saint-Saëns held only one teaching post, at the École de Musique Classique et Religieuse in Paris, and remained there for less than five years. It was nevertheless important in the development of French music: his students included Gabriel Fauré, among whose own later pupils was Maurice Ravel. Both of them were strongly influenced by Saint-Saëns, whom they revered as a genius.', 1835, 1921);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (24, 'Hamburg', 'Independent city-state Hamburg', 'Jakob Ludwig Felix', 'Mendelssohn', 36, 'Jakob Ludwig Felix Mendelssohn Bartholdy (3 February 1809 – 4 November 1847), widely known as Felix Mendelssohn, was a German composer, pianist, organist and conductor of the early Romantic period. Mendelssohn''s compositions include symphonies, concertos, piano music, organ music and chamber music. His best-known works include the overture and incidental music for A Midsummer Night''s Dream (which includes his "Wedding March"), the Italian Symphony, the Scottish Symphony, the oratorio St. Paul, the oratorio Elijah, the overture The Hebrides, the mature Violin Concerto, the String Octet, and the melody used in the Christmas carol "Hark! The Herald Angels Sing". Mendelssohn''s Songs Without Words are his most famous solo piano compositions.

Mendelssohn''s grandfather was the renowned Jewish philosopher Moses Mendelssohn, but Felix was initially raised without religion until he was baptised aged seven into the Reformed Christian church. He was recognised early as a musical prodigy, but his parents were cautious and did not seek to capitalise on his talent. His sister Fanny Mendelssohn received a similar musical education and was a talented composer and pianist in her own right; some of her early songs were published under her brother''s name and her Easter Sonata was for a time mistakenly attributed to him after being lost and rediscovered in the 1970s.

Mendelssohn enjoyed early success in Germany, and revived interest in the music of Johann Sebastian Bach, notably with his performance of the St Matthew Passion in 1829. He became well received in his travels throughout Europe as a composer, conductor and soloist; his ten visits to Britain – during which many of his major works were premiered – form an important part of his adult career. His essentially conservative musical tastes set him apart from more adventurous musical contemporaries such as Franz Liszt, Richard Wagner, Charles-Valentin Alkan and Hector Berlioz. The Leipzig Conservatory, which he founded, became a bastion of this anti-radical outlook. After a long period of relative denigration due to changing musical tastes and antisemitism in the late 19th and early 20th centuries, his creative originality has been re-evaluated. He is now among the most popular composers of the Romantic era.', 1809, 1847);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (25, 'New York City', 'United States of America', 'George', 'Gershwin', 37, 'George Gershwin (/ˈɡɜːrʃ.wɪn/; born Jacob Gershwine; September 26, 1898 – July 11, 1937) was an American composer and pianist whose compositions spanned popular, jazz and classical genres. Among his best-known works are the orchestral compositions Rhapsody in Blue (1924) and An American in Paris (1928), the songs "Swanee" (1919) and "Fascinating Rhythm" (1924), the jazz standards "Embraceable You" (1928) and "I Got Rhythm" (1930), and the opera Porgy and Bess (1935), which included the hit "Summertime".

Gershwin studied piano under Charles Hambitzer and composition with Rubin Goldmark, Henry Cowell, and Joseph Brody. He began his career as a song plugger but soon started composing Broadway theater works with his brother Ira Gershwin and with Buddy DeSylva. He moved to Paris, intending to study with Nadia Boulanger, but she refused him, afraid that rigorous classical study would ruin his jazz-influenced style; Maurice Ravel voiced similar objections when Gershwin inquired about studying with him. He subsequently composed An American in Paris, returned to New York City and wrote Porgy and Bess with Ira and DuBose Heyward. Initially a commercial failure, it came to be considered one of the most important American operas of the 20th century and an American cultural classic.

Gershwin moved to Hollywood and composed numerous film scores. He died in 1937, only 38 years old, of a brain tumor. His compositions have been adapted for use in film and television, with many becoming jazz standards.', 1898, 1937);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (26, 'Lawrence, Massachusetts', 'United States of America', 'Leonard', 'Bernstein', 38, 'Leonard Bernstein (/ˈbɜːrnstaɪn/ BURN-styne) (born Louis Bernstein; August 25, 1918 – October 14, 1990) was an American conductor, composer, pianist, music educator, author, and humanitarian. Considered to be one of the most important conductors of his time, he was the first American-born conductor to receive international acclaim. Bernstein was "one of the most prodigiously talented and successful musicians in American history" according to music critic Donal Henahan. Bernstein''s honors and accolades include seven Emmy Awards, two Tony Awards, and 16 Grammy Awards (including the Lifetime Achievement Award) as well as an Academy Award nomination. He received the Kennedy Center Honor in 1981.

As a composer, Bernstein wrote in many genres, including symphonic and orchestral music, ballet, film and theatre music, choral works, opera, chamber music, and pieces for the piano. Bernstein''s works include the Broadway musical West Side Story, which continues to be regularly performed worldwide, and has been adapted into two (1961 and 2021) feature films, three symphonies, Serenade after Plato''s "Symposium" (1954), and Chichester Psalms (1965), the original score for the Elia Kazan drama film On the Waterfront (1954), and theater works including On the Town (1944), Wonderful Town (1953), Candide (1956), and his Mass (1971).', 1918, 1990);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (27, 'Hamburg ', 'German Confederation', 'Johannes', 'Brahms', 39, 'Johannes Brahms (German: [joˈhanəs ˈbʁaːms]; 7 May 1833 – 3 April 1897) was a German composer, pianist, and conductor of the mid-Romantic period. Born in Hamburg into a Lutheran family, he spent much of his professional life in Vienna. He is sometimes grouped with Johann Sebastian Bach and Ludwig van Beethoven as one of the "Three Bs" of music, a comment originally made by the nineteenth-century conductor Hans von Bülow.

Brahms composed for symphony orchestra, chamber ensembles, piano, organ, voice, and chorus. A virtuoso pianist, he premiered many of his own works. He worked with leading performers of his time, including the pianist Clara Schumann and the violinist Joseph Joachim (the three were close friends). Many of his works have become staples of the modern concert repertoire.

Brahms has been considered both a traditionalist and an innovator, by his contemporaries and by later writers. His music is rooted in the structures and compositional techniques of the Classical masters. Embedded within those structures are deeply Romantic motifs. While some contemporaries found his music to be overly academic, his contribution and craftsmanship were admired by subsequent figures as diverse as Arnold Schoenberg and Edward Elgar. The detailed construction of Brahms''s works was a starting point and an inspiration for a generation of composers.', 1833, 1897);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (28, 'Nelahozeves, near Prague', 'Austrian Empire', 'Antonín Leopold', 'Dvořák', 40, 'Antonín Leopold Dvořák (/d(ə)ˈvɔːrʒɑːk, -ʒæk/ d(ə-)VOR-zha(h)k; Czech: [ˈantoɲiːn ˈlɛopold ˈdvor̝aːk]; 8 September 1841 – 1 May 1904) was a Czech composer. Dvořák frequently employed rhythms and other aspects of the folk music of Moravia and his native Bohemia, following the Romantic-era nationalist example of his predecessor Bedřich Smetana. Dvořák''s style has been described as "the fullest recreation of a national idiom with that of the symphonic tradition, absorbing folk influences and finding effective ways of using them," and he himself has been described as "arguably the most versatile... composer of his time".

Dvořák displayed his musical gifts at an early age, being an apt violin student. The first public performances of his works were in Prague in 1872 and, with special success, in 1873, when he was 31 years old. Seeking recognition beyond the Prague area, he submitted scores of symphonies and other works to German and Austrian competitions. He did not win a prize until 1874, with Johannes Brahms on the jury of the Austrian State Competition. In 1877, after his third win, Brahms recommended Dvořák to his publisher, Simrock, who commissioned what became the Slavonic Dances, Op. 46. The sheet music''s high sales and critical reception led to his international success. A London performance of Dvořák''s Stabat Mater in 1883 led to many other performances in the United Kingdom, the United States, and eventually Russia in March 1890. The Seventh Symphony was written for London in 1885.

In 1892, Dvořák became the director of the National Conservatory of Music of America in New York City. While in the United States, Dvořák wrote his two most successful orchestral works: the Symphony From the New World, which spread his reputation worldwide, and his Cello Concerto, one of the most highly regarded of all cello concerti. On a summer vacation in Spillville, Iowa in 1893, Dvořák also wrote his most famous piece of chamber music, his String Quartet in F major, Op. 96, the American. While he remained at the Conservatory for a few more years, pay cuts and an onset of homesickness led him to return to Bohemia in 1895.

All of Dvořák''s ten operas, except his first, have librettos in Czech and were intended to convey the Czech national spirit, as were some of his choral works. By far the most successful of the operas is Rusalka, premiered in 1901. Among his smaller works, the seventh Humoresque and the song "Songs My Mother Taught Me" are also widely performed and recorded. The Dvořák Prague International Music Festival is a major series of concerts held annually to celebrate Dvořák''s life and works.', 1841, 1904);
INSERT INTO Composers (Id, CityOfBirth, CountryOfBirth, FirstName, LastName, PortraitId, ShortBio, YearOfBirth, YearOfDeath) VALUES (29, 'Ansfelden, near Linz', 'Austrian Empire', 'Josef Anton', 'Bruckner', 41, 'Josef Anton Bruckner (German: [ˈantoːn ˈbʁʊknɐ]; 4 September 1824 – 11 October 1896) was an Austrian composer and organist best known for his symphonies and sacred music, which includes Masses, Te Deum and motets. The symphonies are considered emblematic of the final stage of Austro-German Romanticism because of their rich harmonic language, strongly polyphonic character, and considerable length. Bruckner''s compositions helped to define contemporary musical radicalism, owing to their dissonances, unprepared modulations, and roving harmonies.

Unlike other musical radicals such as Richard Wagner and Hugo Wolf, Bruckner showed respect, even humility, before other famous musicians, Wagner in particular. This apparent dichotomy between Bruckner the man and Bruckner the composer hampers efforts to describe his life in a way that gives a straightforward context for his music. Hans von Bülow described him as "half genius, half simpleton". Bruckner was critical of his own work and often reworked his compositions. There are several versions of many of his works.

His works, the symphonies in particular, had detractors, most notably the influential Austrian critic Eduard Hanslick and other supporters of Johannes Brahms, who pointed to their large size and use of repetition, as well as to Bruckner''s propensity for revising many of his works, often with the assistance of colleagues, and his apparent indecision about which versions he preferred. On the other hand, Bruckner was greatly admired by subsequent composers, including his friend Gustav Mahler.', 1824, 1896);

-- Индекс: IX_Composers_PortraitId
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Composers_PortraitId" ON "Composers" ("PortraitId");

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
